variable "BUCKET_NAME" {}
variable "SANDBOX_ID" {}
variable "USER_CONTENT" {}
variable "SERVER_NAME" {}
variable "SERVER_VERSION" {}
variable "OUTPUT_PUBLISHER_STR" {}
variable "OUTPUT_PUBLISHER_OBJ" {}
variable "OUTPUT_PUBLISHER_MAP" {}
variable "OUTPUT_PUBLISHER_LIST" {}
